# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    ens192:
      dhcp4: no
      addresses:
        - 192.168.197.203/23 # Need to change per VM
      routes:
        - to: default
          via: 192.168.196.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
        search: [wasabilab.io]
    lo:
      addresses:
        - 127.0.0.1/8
        - 192.168.168.167/32  # GakuNin RDM 
